#!/usr/bin/env node
/**
 * Turns the committed Drizzle migrations into one paste-ready SQL script for a
 * database you cannot reach from this machine.
 *
 * Why this exists: `npm run db:migrate` needs a connection, and this project's
 * production Postgres is only reachable from inside its own Docker network. So
 * instead of a connection, this emits SQL you paste into the Postgres service's
 * terminal.
 *
 * What makes it safe to paste repeatedly: each migration is wrapped in a block
 * that runs only if its hash is absent from Drizzle's journal — the same hash
 * `drizzle-kit migrate` computes (sha256 of the file, LF-normalised). Already
 * applied migrations are skipped, and the journal is written exactly as
 * drizzle-kit would write it, so a later `db:migrate` against the same database
 * agrees about what has run.
 *
 * Usage:
 *   npm run db:migrate:sql
 *
 * Then paste the generated file into the Postgres terminal. `COMMIT` at the end
 * means it worked; anything else rolls the whole thing back.
 */

import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const ROOT = process.cwd();
const MIGRATIONS_DIR = path.join(ROOT, "src", "db", "migrations");
const JOURNAL = path.join(MIGRATIONS_DIR, "meta", "_journal.json");
const OUT_FILE = path.join(ROOT, "drizzle-migrate.sql");

/** The hash drizzle-kit stores: sha256 of the file with LF line endings. */
function migrationHash(sql) {
  return createHash("sha256").update(sql.replace(/\r\n/g, "\n")).digest("hex");
}

const journal = JSON.parse(await readFile(JOURNAL, "utf8"));
const entries = journal.entries ?? [];

if (entries.length === 0) {
  console.error("No migrations found in src/db/migrations/meta/_journal.json.");
  process.exit(1);
}

const blocks = [];

for (const [index, entry] of entries.entries()) {
  const file = path.join(MIGRATIONS_DIR, `${entry.tag}.sql`);
  const sql = (await readFile(file, "utf8")).replace(/\r\n/g, "\n").trim();
  const hash = migrationHash(sql);

  // A dollar-quote tag unique per migration, so a migration that itself uses
  // $$ (drizzle emits those for some constraints) cannot terminate our block.
  const tag = `$mig_${entry.tag}$`;
  if (sql.includes(tag)) {
    console.error(`Migration ${entry.tag} contains the quoting tag ${tag}; cannot wrap it safely.`);
    process.exit(1);
  }

  // Drizzle's own statement separator is a comment; harmless inside PL/pgSQL,
  // but stripping it keeps the output readable.
  const body = sql
    .split("--> statement-breakpoint")
    .map((part) => part.trim())
    .filter(Boolean)
    .join("\n\n    ");

  blocks.push(
    [
      `-- ${index + 1}/${entries.length} — ${entry.tag}`,
      `DO ${tag}`,
      `BEGIN`,
      `  IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE hash = '${hash}') THEN`,
      ``,
      `    ${body}`,
      ``,
      `    INSERT INTO "drizzle"."__drizzle_migrations" (hash, created_at)`,
      `    VALUES ('${hash}', (extract(epoch from now()) * 1000)::bigint);`,
      `    RAISE NOTICE 'applied ${entry.tag}';`,
      `  ELSE`,
      `    RAISE NOTICE 'skipped ${entry.tag} (already applied)';`,
      `  END IF;`,
      `END ${tag};`,
    ].join("\n"),
  );
}

const script = [
  `-- Generated by scripts/migrate-sql.mjs — do not edit, and do not commit.`,
  `-- ${entries.length} migration(s). Paste into the Postgres terminal.`,
  `--`,
  `-- Safe to paste more than once: each migration runs only if its hash is`,
  `-- absent from Drizzle's journal, and the whole script is one transaction.`,
  `-- "COMMIT" at the end means it worked.`,
  ``,
  `BEGIN;`,
  ``,
  `CREATE SCHEMA IF NOT EXISTS "drizzle";`,
  `CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (`,
  `  id SERIAL PRIMARY KEY,`,
  `  hash text NOT NULL,`,
  `  created_at bigint`,
  `);`,
  ``,
  ...blocks,
  ``,
  `COMMIT;`,
  ``,
].join("\n");

await writeFile(OUT_FILE, script);

console.log(`Wrote ${path.relative(ROOT, OUT_FILE)} — ${entries.length} migration(s):`);
for (const entry of entries) console.log(`  ${entry.tag}`);
console.log(`\nPaste it into the Postgres service terminal:`);
console.log(`  psql -U postgres -d postgres <<'SQL'`);
console.log(`  …contents of ${path.relative(ROOT, OUT_FILE)}…`);
console.log(`  SQL`);
console.log(`\nAlready-applied migrations are skipped, so pasting it twice is harmless.`);
